packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@base-ui/react": ^1.4.0
  "@excalidraw/excalidraw": ^0.18.0
  "@hugeicons/core-free-icons": ^4.1.1
  "@hugeicons/react": ^1.1.6
  "@lana/utils": workspace:*
  "@lexical/html": ^0.43.0
  "@types/katex": ^0.16.8
  "@types/node": ^24
  autoprefixer: ^10.5.0
  class-variance-authority: ^0.7.1
  katex: ^0.16.45
  next-themes: ^0.4.6
  postcss: ^8.5.10
  react-error-boundary: ^6.1.1
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
