packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@base-ui/react": ^1.4.0
  "@changesets/cli": ^2.31.0
  "@fontsource/geist-mono": ^5.2.7
  "@fontsource/instrument-serif": ^5.2.8
  "@andi/utils": workspace:*
  "@tanstack/react-router": ^1.168.25
  "@types/node": ^24
  autoprefixer: ^10.5.0
  class-variance-authority: ^0.7.1
  katex: ^0.16.45
  andi-editor: file:../packages/editor-pkg/andi-editor-0.3.1.tgz
  next-themes: ^0.4.6
  postcss: ^8.5.10
  react-error-boundary: ^6.1.1
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-dts: ^4.5.4
  vite-plus: ^0.1.18
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
